USE [PSRegExp];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[Customers]
(
    [ID] [INT] NOT NULL,
    [NAME] [NVARCHAR](24) NULL,
    [COMPANY_NAME] [NVARCHAR](100) NULL,
    CONSTRAINT [PK_Customers]
        PRIMARY KEY CLUSTERED ([ID] ASC)
        WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
              ALLOW_PAGE_LOCKS = ON
             ) ON [PRIMARY]
) ON [PRIMARY];
GO


